In [20]:
import pandas as pd
data = {
    'name': ['Анна', 'Борис', 'Вика', 'Денис', 'Елена'],
    'age': [21, 22, 23, 24, 15],
    'city': ['Москва', 'Санкт-Петербург', 'Казань', 'Москва', 'Сочи'],
    'math_grade': [85, 92, 88, 78, 95],
    'physics_grade': [90, 89, 85, 88, 92]
}

df = pd.DataFrame(data)
# Посмотри на первые 3 строки датафрейма с помощью head().
df.head(3)

    name  age             city  math_grade  physics_grade
0   Анна   21           Москва          85             90
1  Борис   22  Санкт-Петербург          92             89
2   Вика   23           Казань          88             85

In [21]:
# Посмотри на последние 2 строки датафрейма с помощью tail().
df.tail(2)

    name  age    city  math_grade  physics_grade
3  Денис   24  Москва          78             88
4  Елена   15    Сочи          95             92

In [4]:
# Получите информацию о DataFrame, чтобы проверить типы данных и другие свойства с помощью info().
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           5 non-null      object
 1   age            5 non-null      int64
 2   city           5 non-null      object
 3   math_grade     5 non-null      int64
 4   physics_grade  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

In [23]:
# 5. Добавление нового столбца average_grade
df['average_grade'] = (df['math_grade'] + df['physics_grade']) / 2
df.head()

    name  age             city  math_grade  physics_grade  average_grade
0   Анна   21           Москва          85             90           87.5
1  Борис   22  Санкт-Петербург          92             89           90.5
2   Вика   23           Казань          88             85           86.5
3  Денис   24           Москва          78             88           83.0
4  Елена   15             Сочи          95             92           93.5

In [22]:
# Отфильтруй студентов, у которых возраст больше 22 лет, и выведи результат.
df_filtered = df[df['age'] > 22]
df_filtered

    name  age    city  math_grade  physics_grade
2   Вика   23  Казань          88             85
3  Денис   24  Москва          78             88

In [27]:
df['isPassed'] = (df['average_grade'] >= 90)
df['isPassed']

0    False
1     True
2    False
3    False
4     True
Name: isPassed, dtype: bool

In [29]:
df.to_csv('data.csv', index=False)
df

,name,age,city,math_grade,physics_grade,average_grade,isPassed
0,Анна,21,Москва,85,90,87.5,False
1,Борис,22,Санкт-Петербург,92,89,90.5,True
2,Вика,23,Казань,88,85,86.5,False
3,Денис,24,Москва,78,88,83.0,False
4,Елена,15,Сочи,95,92,93.5,True